### ISSUE TITLE
Choosing config storage strategy

### ISSUE THREAD

**Issue by snowwm** [AskfmForHumans/afh-bot#1]
### What we need to store

| Config type | Examples | Managed by |
|-|-|-|
| global | enabled features, UI messages/localizations | admins |
| global secrets | API tokens and other credentials | admins |
| user | enabled features (`autoblock`, `filter="go mutual likes"`) | users |
| user meta | user access token and some metadata | users/app |

### What storage options we have

| Storage type | Config type | Capacity | Management | Pros | Cons |
|-|-|-|-|-|-|
| env variables | global | medium | easy |  | needs app restart (at least on Heroku) |
| cloud config service (e.g. https://config.ly/) | global | high | easy |  |  |
| database | global | high | medium |  |  |
| database | user | high | hard (need to create an interface) |  | non-transparent for users |
| profile description | user | low (300 characters including user's own info) | easy | decentralized | messes user's personal info |
| profile hashtags | user | low (50 lowercase letters per hashtag) | almost easy | decentralized | messes user's personal info |

### More on user config

I prefer decentralized approaches, so I'm after storing user config in users' own profiles.

Credentials are an important subtype of user config. ASKfm doesn't support OAuth (sigh), but we can use the user's password to get an access token and store that token. This is practically OAuth. The downside is that it can require manual re-logins when the token gets invalidated.

Storing credentials on users' profiles obviously requires encryption.
Symmetric is simple and secure, but I think asymmetric is more flexible as it enables more auth flows. Tech-savvy users may generate and encrypt the token themselves or we can offer a client-side utility for it.
A promising option is [eciespy](https://github.com/ecies/py), which requires just 97 + *data size* bytes and provides integrity guarantees on top of encryption.

In the end, storing credentials on users' profiles seems impractical since:
- it requires complex encryption logic
- it takes much space
- credentials don't need to be directly managed by users

### Proposed scheme

| Config type | Storage type |
|-|-|
| global | database |
| global secrets | env variables |
| user | profile description |
| user meta | database |

### Roadmap

- [x] move user config to profile description
- [x] provision a DB
- [x] move global config to DB
- [x] move user data to DB
- [ ] move UI strings to DB

**Comment by snowwm** [comment]
Won't move UI strings to the DB as the benefit from it is not obvious and there are way more important tasks.
